Repository release-drafter/release-drafter, pull requests merged in 2020-01, with the labels that each got.

#367 Prevent untagged-<hash> being set as tag name
  index.js
Labels: type: bug

#368 Config schema validation improvements
  lib/config.js
  lib/schema.js
  lib/utils.js
  package.json
  test/schema.test.js
  yarn.lock
Labels: type: maintenance

#350 Allow specifying the config name through an input option
  README.md
  index.js
  lib/config.js
  test/fixtures/config/config-name-input.yml
  test/helpers/config-mock.js
  test/index.test.js
Labels: type: feature, waiting on release window

#384 Fix draft update from failing
  index.js
Labels: type: bug

#363 Override calculated version, tag and name with input
  index.js
  lib/releases.js
  lib/template.js
  lib/versions.js
  package.json
  test/fixtures/config/config-with-input-version-template.yml
  test/fixtures/config/config-with-resolved-version-template.yml
  test/index.test.js
  yarn.lock
Labels: type: feature
